services:
  postgrest:
    image: postgrest/postgrest
    restart: always
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://app_user:${POSTGRES_PASSWORD}@db:5432/app_db
      PGRST_DB_SCHEMAS: public
      PGRST_DB_ANON_ROLE: web_anon
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
    depends_on:
      - db
  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - "${WF_DATA_DIR}/postgres_data:/var/lib/postgresql/data"
      - ./database:/docker-entrypoint-initdb.d

  restape:
    image: ghcr.io/sanctuuary/restape:latest
    restart: always
    ports:
      - "8080:4444"
  
  pubmetric:
    image: ghcr.io/workflomics/pubmetric:pr-43
    restart: always
    ports:
      - "8000:8000"

networks:
  default:
    driver: bridge
