# Verbindung zur Datenbank
db-uri = "postgres://db_user:root@localhost:5432/workflomics"

# Welches Schema soll über die API erreichbar sein?
# Da deine Tabellen in "public" liegen:
db-schema = "public"

# Die Rolle für nicht authentifizierte Anfragen
db-anon-role = "web_anon"

# Der Port, auf dem die API lauscht
server-port = 3001